# Generated by Django 4.2 on 2023-04-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                ("empno", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=50)),
                ("deptno", models.IntegerField()),
            ],
        ),
    ]
