# Generated by Django 4.2 on 2023-04-10 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("writer", models.CharField(blank=True, max_length=50, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                (
                    "post_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
