# Generated by Django 4.2 on 2023-04-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=50, null=True)),
                ("sal", models.IntegerField()),
                ("bonus", models.IntegerField()),
                ("total", models.IntegerField()),
                ("tax", models.IntegerField()),
                ("money", models.IntegerField()),
            ],
        ),
    ]
